spring.application.name=Randevu-App
spring.output.ansi.enabled=always
app.base-url=http://localhost:8080
app.frontend-url=http://localhost:3000
spring.datasource.url=jdbc:postgresql://localhost:5432/postgres
spring.datasource.username=postgres
spring.datasource.password=1979
spring.jpa.properties.hibernate.default_schema=randevu-app
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=create
logging.level.org.springframework.security=DEBUG
spring.jpa.properties.hibernate.format_sql=true
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=aleykedu@gmail.com
spring.mail.password=yrmm phry ncce xoyi
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
auth-core.secret-key=key
auth-core.expiration-ms=86400000
auth-core.enable-oauth=false
# Note: Use array index notation [0], [1]...
auth-core.whitelist[0]=/auth/**
auth-core.whitelist[1]=/public/**
auth-core.whitelist[2]=/swagger-ui/**
auth-core.whitelist[3]=/v3/api-docs/**
auth-core.whitelist[4]=/test/**
auth-core.whitelist[5]=/api/v1/verification/**
auth-core.whitelist[6]=/auth/forgot-password/**

# Security
app.security.phone-verification-validity-days=365
app.security.email-verification-validity-days=180

# Verification Settings
app.verification.token-validity-minutes=15
app.verification.max-attempts=3
app.verification.code-length=6
app.verification.password-reset-token-validity-minutes=15

# Spam Protection
app.verification.spam.max-requests-per-block=5
app.verification.spam.block-duration-minutes=30

# Redis
spring.data.redis.host=localhost
spring.data.redis.port=6379
